import {describe, expect, it} from "vitest";
import {
  buildDeferDecisions,
  deferEmptyCatalogEntries,
  findEmptyEntries,
} from "../defer-empty-catalog-entries.mjs";
import {mkdtempSync, mkdirSync, readFileSync, writeFileSync} from "node:fs";
import {tmpdir} from "node:os";
import path from "node:path";

function makeTestCatalog(entries) {
  return {
    source: "test-fixture",
    generatedAt: new Date().toISOString(),
    count: entries.length,
    entries,
  };
}

function makeTestDecisions(version, decisions) {
  return {version, decisions};
}

function makeEntry(overrides = {}) {
  return {
    id: overrides.id ?? "test--form--usul--title--composer",
    makam: overrides.makam ?? "test",
    form: overrides.form ?? "form",
    usul: overrides.usul ?? "usul",
    title: overrides.title ?? "title",
    composer: overrides.composer ?? "composer",
    formats: overrides.formats ?? ["txt", "mid"],
  };
}

describe("defer empty catalog entries", () => {
  it("identifies 82 both-empty entries from catalog", () => {
    const catalog = makeTestCatalog([
      makeEntry({id: "a--x--y--title--composer", title: "title", composer: "composer"}),
      makeEntry({id: "b--x--y--1--", title: "1", composer: ""}),
      makeEntry({id: "c--x--y---", title: "", composer: ""}),
      makeEntry({id: "d--x--y--1--hascomposer", title: "1", composer: "hascomposer"}),
      makeEntry({id: "e--x--y--title--", title: "title", composer: ""}),
      makeEntry({id: "f--x--y--1--", title: "1", composer: ""}),
    ]);

    const empty = findEmptyEntries(catalog.entries);

    expect(empty).toHaveLength(3);
    expect(empty.map((e) => e.id)).toEqual(["b--x--y--1--", "c--x--y---", "f--x--y--1--"]);
  });

  it("merges with existing decisions, no duplicates", () => {
    const existing = makeTestDecisions(1, [
      {catalogId: "b--x--y--1--", status: "needs-disambiguation", reason: "Already reviewed"},
    ]);

    const emptyEntries = [
      makeEntry({id: "b--x--y--1--", title: "1", composer: ""}),
      makeEntry({id: "c--x--y---", title: "", composer: ""}),
      makeEntry({id: "f--x--y--1--", title: "1", composer: ""}),
    ];

    const newDecisions = buildDeferDecisions(emptyEntries, existing.decisions, "scripts/lib/defer-empty-catalog-entries.mjs");

    expect(newDecisions).toHaveLength(2);
    expect(newDecisions.map((d) => d.catalogId)).toEqual(["c--x--y---", "f--x--y--1--"]);

    for (const d of newDecisions) {
      expect(d.status).toBe("deferred");
      expect(d.reason).toBe("empty-title-and-composer-cannot-auto-discover");
      expect(d.autoGenerated).toBe(true);
      expect(d.source).toBe("scripts/lib/defer-empty-catalog-entries.mjs");
      expect(d.decidedAt).toBeTruthy();
    }
  });

  it("dry-run mode does not write files", () => {
    const root = mkdtempSync(path.join(tmpdir(), "muzik-defer-empty-"));
    const dataDir = path.join(root, "src", "data");
    mkdirSync(path.join(dataDir, "symbtr"), {recursive: true});
    mkdirSync(path.join(dataDir, "references"), {recursive: true});

    const catalog = makeTestCatalog([
      makeEntry({id: "a--x--y--title--composer", title: "title", composer: "composer"}),
      makeEntry({id: "b--x--y--1--", title: "1", composer: ""}),
    ]);

    const decisions = makeTestDecisions(1, [
      {catalogId: "existing--entry", status: "needs-disambiguation"},
    ]);

    writeFileSync(
      path.join(dataDir, "symbtr", "catalog.generated.json"),
      `${JSON.stringify(catalog, null, 2)}\n`,
    );
    writeFileSync(
      path.join(dataDir, "references", "external-curation-decisions.json"),
      `${JSON.stringify(decisions, null, 2)}\n`,
    );

    const catalogPath = path.join("src", "data", "symbtr", "catalog.generated.json");
    const decisionsPath = path.join("src", "data", "references", "external-curation-decisions.json");

    const beforeContent = readFileSync(path.join(root, decisionsPath), "utf8");

    const result = deferEmptyCatalogEntries({
      root,
      catalogPath,
      decisionsPath,
      write: false,
    });

    expect(result.emptyEntryCount).toBe(1);
    expect(result.existingDecisionCount).toBe(1);
    expect(result.newDecisionCount).toBe(1);
    expect(result.wrote).toBe(false);

    const afterContent = readFileSync(path.join(root, decisionsPath), "utf8");
    expect(afterContent).toBe(beforeContent);

    // Now write mode
    const writeResult = deferEmptyCatalogEntries({
      root,
      catalogPath,
      decisionsPath,
      write: true,
    });

    expect(writeResult.wrote).toBe(true);
    expect(writeResult.totalDecisionCount).toBe(2);

    const writtenContent = readFileSync(path.join(root, decisionsPath), "utf8");
    const written = JSON.parse(writtenContent);
    expect(written.version).toBe(1);
    expect(written.decisions).toHaveLength(2);
  });
});
