import {Usul} from "@/types";

export const USUL_DATA: Usul[] = [
  {
    id: "nimsofyan",
    name: "Nimsofyan",
    nameTr: "Nimsofyan",
    nameEn: "Nimsofyan",
    beats: 2,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0],
  },
  {
    id: "semai",
    name: "Semai",
    nameTr: "Semai",
    nameEn: "Semai",
    beats: 3,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0],
  },
  {
    id: "sofyan",
    name: "Sofyan",
    nameTr: "Sofyan",
    nameEn: "Sofyan",
    beats: 4,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0],
  },
  {
    id: "nimhafif",
    name: "Nimhafif",
    nameTr: "Nimhafif",
    nameEn: "Nimhafif",
    beats: 4,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0],
  },
  {
    id: "turkaksagi",
    name: "Türk Aksağı",
    nameTr: "Türk Aksağı",
    nameEn: "Turkish Aksak",
    beats: 5,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
    ],
    stressPattern: [1, 0, 0, 0, 1],
  },
  {
    id: "zafer",
    name: "Zafer",
    nameTr: "Zafer",
    nameEn: "Zafer",
    beats: 5,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 1},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 2},
      {beat: 3, symbol: "dum", isAccent: true, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1],
  },
  {
    id: "yuruksemai",
    name: "Yürüksemâî",
    nameTr: "Yürüksemâî",
    nameEn: "Yuruksemai",
    beats: 6,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 5, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0],
  },
  {
    id: "senginsemai",
    name: "Sengin Semai",
    nameTr: "Sengin Semai",
    nameEn: "Sengin Semai",
    beats: 6,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 5, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 1, 0, 0],
  },
  {
    id: "agirsemai",
    name: "Ağır Semai",
    nameTr: "Ağır Semai",
    nameEn: "Agir Semai",
    beats: 6,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0],
  },
  {
    id: "darb",
    name: "Darb",
    nameTr: "Darb",
    nameEn: "Darb",
    beats: 6,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 5, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 1, 0, 0],
  },
  {
    id: "devirhindi",
    name: "Devr-i Hindi",
    nameTr: "Devr-i Hindi",
    nameEn: "Devr-i Hindi",
    beats: 7,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 5, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "ke", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "devirituran",
    name: "Devr-i Turan",
    nameTr: "Devr-i Turan",
    nameEn: "Devr-i Turan",
    beats: 7,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 5, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 6, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "duyek",
    name: "Düyek",
    nameTr: "Düyek",
    nameEn: "Duyek",
    beats: 8,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "agirduyek",
    name: "Ağırdüyek",
    nameTr: "Ağırdüyek",
    nameEn: "Agirduyek",
    beats: 8,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 5, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 1, 0, 0, 1, 0],
  },
  {
    id: "musemmen",
    name: "Müsemmen",
    nameTr: "Müsemmen",
    nameEn: "Musemmen",
    beats: 8,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "aksak",
    name: "Aksak",
    nameTr: "Aksak",
    nameEn: "Aksak",
    beats: 9,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 5, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "ke", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 1, 0, 0, 1, 0, 0],
  },
  {
    id: "curcuna",
    name: "Curcuna",
    nameTr: "Curcuna",
    nameEn: "Curcuna",
    beats: 10,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 5, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 6, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 10, symbol: "ke", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 1, 0, 0, 0, 0, 1, 0],
  },
  {
    id: "agiraksak",
    name: "Ağır Aksak",
    nameTr: "Ağır Aksak",
    nameEn: "Agir Aksak",
    beats: 9,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 5, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "ke", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 1, 0, 0, 1, 0, 0],
  },
  {
    id: "oynak",
    name: "Oynak",
    nameTr: "Oynak",
    nameEn: "Oynak",
    beats: 9,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "ke", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 0],
  },
  {
    id: "evfer",
    name: "Evfer",
    nameTr: "Evfer",
    nameEn: "Evfer",
    beats: 9,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "dum", isAccent: true, timeValue: 2},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1],
  },
  {
    id: "ciftesofyan",
    name: "Çiftesofyan",
    nameTr: "Çiftesofyan",
    nameEn: "Ciftesofyan",
    beats: 9,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "dum", isAccent: true, timeValue: 2},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1],
  },
  {
    id: "lenkfahte",
    name: "Lenk Fahte",
    nameTr: "Lenk Fahte",
    nameEn: "Lenk Fahte",
    beats: 10,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 10, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0],
  },
  {
    id: "aksaksemai",
    name: "Aksaksemaî",
    nameTr: "Aksaksemaî",
    nameEn: "Aksaksemai",
    beats: 10,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 10, symbol: "ke", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0],
  },
  {
    id: "frenkcin",
    name: "Frenkçin",
    nameTr: "Frenkçin",
    nameEn: "Frenkcin",
    beats: 12,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 10, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 11, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 12, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "nimcember",
    name: "Nim Çember",
    nameTr: "Nim Çember",
    nameEn: "Nim Cember",
    beats: 12,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 10, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 11, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 12, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "devrirevan",
    name: "Devrirevan",
    nameTr: "Devrirevan",
    nameEn: "Devrirevan",
    beats: 14,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 10, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 11, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 12, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 13, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 14, symbol: "ke", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0],
  },
  {
    id: "nimberafsan",
    name: "Nim Berafsan",
    nameTr: "Nim Berafsan",
    nameEn: "Nim Berafsan",
    beats: 16,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 10, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 11, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 12, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 13, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 14, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 15, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 16, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "raksan",
    name: "Raksan",
    nameTr: "Raksan",
    nameEn: "Raksan",
    beats: 15,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 10, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 11, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 12, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 13, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 14, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 15, symbol: "ke", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
  },
  {
    id: "cember",
    name: "Çember",
    nameTr: "Çember",
    nameEn: "Cember",
    beats: 24,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 10, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 11, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 12, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 13, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 14, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 15, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 16, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 17, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 18, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 19, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 20, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 21, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 22, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 23, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 24, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "hafif",
    name: "Hafif",
    nameTr: "Hafif",
    nameEn: "Hafif",
    beats: 32,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 10, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 11, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 12, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 13, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 14, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 15, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 16, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 17, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 18, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 19, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 20, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 21, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 22, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 23, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 24, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 25, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 26, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 27, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 28, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 29, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 30, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 31, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 32, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "devrikebir",
    name: "Devr-i Kebir",
    nameTr: "Devr-i Kebir",
    nameEn: "Devr-i Kebir",
    beats: 28,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 5, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 10, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 11, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 12, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 13, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 14, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 15, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 16, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 17, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 18, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 19, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 20, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 21, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 22, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 23, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 24, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 25, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 26, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 27, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 28, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "fahte",
    name: "Fahte",
    nameTr: "Fahte",
    nameEn: "Fahte",
    beats: 20,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 10, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 11, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 12, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 13, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 14, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 15, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 16, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 17, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 18, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 19, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 20, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "berafsan",
    name: "Berafsan",
    nameTr: "Berafsan",
    nameEn: "Berafsan",
    beats: 32,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 10, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 11, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 12, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 13, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 14, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 15, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 16, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 17, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 18, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 19, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 20, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 21, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 22, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 23, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 24, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 25, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 26, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 27, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 28, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 29, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 30, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 31, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 32, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "darbiturki",
    name: "Darb-ı Türkı",
    nameTr: "Darb-ı Türkı",
    nameEn: "Darb-i Turki",
    beats: 20,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 2, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 3, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 4, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 5, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 6, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 7, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 8, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 9, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 10, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 11, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 12, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 13, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 14, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 15, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 16, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 17, symbol: "dum", isAccent: true, timeValue: 2},
      {beat: 18, symbol: "tek", isAccent: false, timeValue: 1},
      {beat: 19, symbol: "ke", isAccent: false, timeValue: 1},
      {beat: 20, symbol: "tek", isAccent: false, timeValue: 1},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "darbifeth",
    name: "Darb-ı Feth",
    nameTr: "Darb-ı Feth",
    nameEn: "Darb-i Feth",
    beats: 88,
    unit: "4",
    symbols: Array.from({length: 88}, (_, i) => ({
      beat: i + 1,
      symbol: (i % 4 === 0) ? "dum" : (i % 2 === 0 ? "ke" : "tek") as "dum" | "tek" | "ke" | "",
      isAccent: i % 4 === 0,
      timeValue: i % 4 === 0 ? 2 : 1,
    })),
    stressPattern: Array.from({length: 88}, (_, i) => (i % 4 === 0 ? 1 : 0)),
  },
  {
    id: "zincir",
    name: "Zincir",
    nameTr: "Zincir",
    nameEn: "Zincir",
    beats: 88,
    unit: "4",
    symbols: Array.from({length: 88}, (_, i) => ({
      beat: i + 1,
      symbol: (i % 4 === 0) ? "dum" : (i % 2 === 0 ? "ke" : "tek") as "dum" | "tek" | "ke" | "",
      isAccent: i % 4 === 0,
      timeValue: i % 4 === 0 ? 2 : 1,
    })),
    stressPattern: Array.from({length: 88}, (_, i) => (i % 4 === 0 ? 1 : 0)),
  },
];

export function getUsulById(id: string): Usul | undefined {
  return USUL_DATA.find((u) => u.id === id);
}

export function getUsulBeatDuration(usul: Usul, bpm: number): number {
  const beatUnit = parseInt(usul.unit);
  return (60 / bpm) * (4 / beatUnit);
}
