import {Usul} from "@/types";

export const USUL_DATA: Usul[] = [
  {
    id: "aksaksemai",
    name: "Aksak Semai",
    nameTr: "Aksak Semai",
    nameEn: "Aksak Semai",
    beats: 9,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
      {beat: 7, symbol: "ke", isAccent: false},
      {beat: 8, symbol: "tek", isAccent: false},
      {beat: 9, symbol: "dum", isAccent: true},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1],
  },
  {
    id: "duyek",
    name: "Düyek",
    nameTr: "Düyek",
    nameEn: "Düyek",
    beats: 2,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
    ],
    stressPattern: [1, 0],
  },
  {
    id: "sofyan",
    name: "Sofyan",
    nameTr: "Sofyan",
    nameEn: "Sofyan",
    beats: 4,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0],
  },
  {
    id: "turkaksagi",
    name: "Türk Aksağı",
    nameTr: "Türk Aksağı",
    nameEn: "Turkish Aksak",
    beats: 9,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "tek", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
      {beat: 7, symbol: "tek", isAccent: false},
      {beat: 8, symbol: "tek", isAccent: false},
      {beat: 9, symbol: "dum", isAccent: true},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1],
  },
  {
    id: "semai",
    name: "Semai",
    nameTr: "Semai",
    nameEn: "Semai",
    beats: 6,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0],
  },
  {
    id: "hafif",
    name: "Hafif",
    nameTr: "Hafif",
    nameEn: "Hafif",
    beats: 8,
    unit: "9",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
      {beat: 7, symbol: "ke", isAccent: false},
      {beat: 8, symbol: "tek", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "devanegir",
    name: "Devir-i Hindi",
    nameTr: "Devir-i Hindi",
    nameEn: "Devre-i Hindi",
    beats: 16,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
      {beat: 7, symbol: "ke", isAccent: false},
      {beat: 8, symbol: "tek", isAccent: false},
      {beat: 9, symbol: "dum", isAccent: true},
      {beat: 10, symbol: "tek", isAccent: false},
      {beat: 11, symbol: "ke", isAccent: false},
      {beat: 12, symbol: "tek", isAccent: false},
      {beat: 13, symbol: "dum", isAccent: true},
      {beat: 14, symbol: "tek", isAccent: false},
      {beat: 15, symbol: "ke", isAccent: false},
      {beat: 16, symbol: "tek", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "berefşan",
    name: "Berefşan",
    nameTr: "Berefşan",
    nameEn: "Berefshan",
    beats: 6,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "ke", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0],
  },
  {
    id: "çenber",
    name: "Çenber",
    nameTr: "Çenber",
    nameEn: "Chenber",
    beats: 10,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
      {beat: 7, symbol: "ke", isAccent: false},
      {beat: 8, symbol: "tek", isAccent: false},
      {beat: 9, symbol: "dum", isAccent: true},
      {beat: 10, symbol: "tek", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0],
  },
  {
    id: "devirhurde",
    name: "Devirhurde",
    nameTr: "Devirhurde",
    nameEn: "Devirhurde",
    beats: 32,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
      {beat: 7, symbol: "ke", isAccent: false},
      {beat: 8, symbol: "tek", isAccent: false},
      {beat: 9, symbol: "dum", isAccent: true},
      {beat: 10, symbol: "tek", isAccent: false},
      {beat: 11, symbol: "ke", isAccent: false},
      {beat: 12, symbol: "tek", isAccent: false},
      {beat: 13, symbol: "dum", isAccent: true},
      {beat: 14, symbol: "tek", isAccent: false},
      {beat: 15, symbol: "ke", isAccent: false},
      {beat: 16, symbol: "tek", isAccent: false},
      {beat: 17, symbol: "dum", isAccent: true},
      {beat: 18, symbol: "tek", isAccent: false},
      {beat: 19, symbol: "ke", isAccent: false},
      {beat: 20, symbol: "tek", isAccent: false},
      {beat: 21, symbol: "dum", isAccent: true},
      {beat: 22, symbol: "tek", isAccent: false},
      {beat: 23, symbol: "ke", isAccent: false},
      {beat: 24, symbol: "tek", isAccent: false},
      {beat: 25, symbol: "dum", isAccent: true},
      {beat: 26, symbol: "tek", isAccent: false},
      {beat: 27, symbol: "ke", isAccent: false},
      {beat: 28, symbol: "tek", isAccent: false},
      {beat: 29, symbol: "dum", isAccent: true},
      {beat: 30, symbol: "tek", isAccent: false},
      {beat: 31, symbol: "ke", isAccent: false},
      {beat: 32, symbol: "tek", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "fahte",
    name: "Fahte",
    nameTr: "Fahte",
    nameEn: "Fahte",
    beats: 4,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "ke", isAccent: false},
      {beat: 3, symbol: "tek", isAccent: false},
      {beat: 4, symbol: "ke", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0],
  },
  {
    id: "grubunsema",
    name: "Grubunsema",
    nameTr: "Grubunsema",
    nameEn: "Grubunsema",
    beats: 9,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
      {beat: 7, symbol: "ke", isAccent: false},
      {beat: 8, symbol: "tek", isAccent: false},
      {beat: 9, symbol: "ke", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 0],
  },
  {
    id: "hareket",
    name: "Hareket",
    nameTr: "Hareket",
    nameEn: "Hareket",
    beats: 5,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "ke", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 0],
  },
  {
    id: "haza",
    name: "Haza",
    nameTr: "Haza",
    nameEn: "Haza",
    beats: 10,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
      {beat: 7, symbol: "ke", isAccent: false},
      {beat: 8, symbol: "tek", isAccent: false},
      {beat: 9, symbol: "dum", isAccent: true},
      {beat: 10, symbol: "ke", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0],
  },
  {
    id: "kavar",
    name: "Kavar",
    nameTr: "Kavar",
    nameEn: "Kavar",
    beats: 5,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "tek", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
    ],
    stressPattern: [1, 0, 0, 0, 1],
  },
  {
    id: "muzaf",
    name: "Muzaf",
    nameTr: "Muzaf",
    nameEn: "Muzaf",
    beats: 12,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
      {beat: 7, symbol: "ke", isAccent: false},
      {beat: 8, symbol: "tek", isAccent: false},
      {beat: 9, symbol: "dum", isAccent: true},
      {beat: 10, symbol: "tek", isAccent: false},
      {beat: 11, symbol: "ke", isAccent: false},
      {beat: 12, symbol: "tek", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "nimsofyan",
    name: "Nimsofyan",
    nameTr: "Nimsofyan",
    nameEn: "Nimsofyan",
    beats: 2,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "ke", isAccent: false},
    ],
    stressPattern: [1, 0],
  },
  {
    id: "oyunhavasi",
    name: "Oyunhavası",
    nameTr: "Oyunhavası",
    nameEn: "Oyun Havasi",
    beats: 8,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
      {beat: 7, symbol: "ke", isAccent: false},
      {beat: 8, symbol: "tek", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "punar",
    name: "Punar",
    nameTr: "Punar",
    nameEn: "Punar",
    beats: 18,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
      {beat: 7, symbol: "ke", isAccent: false},
      {beat: 8, symbol: "tek", isAccent: false},
      {beat: 9, symbol: "dum", isAccent: true},
      {beat: 10, symbol: "tek", isAccent: false},
      {beat: 11, symbol: "ke", isAccent: false},
      {beat: 12, symbol: "tek", isAccent: false},
      {beat: 13, symbol: "dum", isAccent: true},
      {beat: 14, symbol: "tek", isAccent: false},
      {beat: 15, symbol: "ke", isAccent: false},
      {beat: 16, symbol: "tek", isAccent: false},
      {beat: 17, symbol: "dum", isAccent: true},
      {beat: 18, symbol: "ke", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0],
  },
  {
    id: "sakil",
    name: "Sakil",
    nameTr: "Sakil",
    nameEn: "Sakil",
    beats: 14,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
      {beat: 7, symbol: "ke", isAccent: false},
      {beat: 8, symbol: "tek", isAccent: false},
      {beat: 9, symbol: "dum", isAccent: true},
      {beat: 10, symbol: "tek", isAccent: false},
      {beat: 11, symbol: "ke", isAccent: false},
      {beat: 12, symbol: "tek", isAccent: false},
      {beat: 13, symbol: "dum", isAccent: true},
      {beat: 14, symbol: "ke", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0],
  },
  {
    id: "santibreg",
    name: "Santibreg",
    nameTr: "Santibreg",
    nameEn: "Santibre",
    beats: 9,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "tek", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
      {beat: 7, symbol: "tek", isAccent: false},
      {beat: 8, symbol: "tek", isAccent: false},
      {beat: 9, symbol: "ke", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 0],
  },
  {
    id: "serhafif",
    name: "Serhafif",
    nameTr: "Serhafif",
    nameEn: "Serhafif",
    beats: 16,
    unit: "9",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
      {beat: 7, symbol: "ke", isAccent: false},
      {beat: 8, symbol: "tek", isAccent: false},
      {beat: 9, symbol: "dum", isAccent: true},
      {beat: 10, symbol: "tek", isAccent: false},
      {beat: 11, symbol: "ke", isAccent: false},
      {beat: 12, symbol: "tek", isAccent: false},
      {beat: 13, symbol: "dum", isAccent: true},
      {beat: 14, symbol: "tek", isAccent: false},
      {beat: 15, symbol: "ke", isAccent: false},
      {beat: 16, symbol: "tek", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
  },
  {
    id: "serhildek",
    name: "Serhildek",
    nameTr: "Serhildek",
    nameEn: "Serhildek",
    beats: 6,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0],
  },
  {
    id: "türkaaksak",
    name: "Türk Aksağı",
    nameTr: "Türk Aksağı",
    nameEn: "Turkish Aksak",
    beats: 9,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "tek", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
      {beat: 7, symbol: "tek", isAccent: false},
      {beat: 8, symbol: "tek", isAccent: false},
      {beat: 9, symbol: "dum", isAccent: true},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1],
  },
  {
    id: "yuruksema",
    name: "Yürük Semai",
    nameTr: "Yürük Semai",
    nameEn: "Yuruksema",
    beats: 5,
    unit: "4",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "ke", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 0],
  },
  {
    id: "zencir",
    name: "Zencir",
    nameTr: "Zencir",
    nameEn: "Zencir",
    beats: 14,
    unit: "8",
    symbols: [
      {beat: 1, symbol: "dum", isAccent: true},
      {beat: 2, symbol: "tek", isAccent: false},
      {beat: 3, symbol: "ke", isAccent: false},
      {beat: 4, symbol: "tek", isAccent: false},
      {beat: 5, symbol: "dum", isAccent: true},
      {beat: 6, symbol: "tek", isAccent: false},
      {beat: 7, symbol: "ke", isAccent: false},
      {beat: 8, symbol: "tek", isAccent: false},
      {beat: 9, symbol: "dum", isAccent: true},
      {beat: 10, symbol: "tek", isAccent: false},
      {beat: 11, symbol: "ke", isAccent: false},
      {beat: 12, symbol: "tek", isAccent: false},
      {beat: 13, symbol: "dum", isAccent: true},
      {beat: 14, symbol: "tek", isAccent: false},
    ],
    stressPattern: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0],
  },
];

export function getUsulById(id: string): Usul | undefined {
  return USUL_DATA.find((u) => u.id === id);
}

export function getUsulBeatDuration(usul: Usul, bpm: number): number {
  const beatUnit = parseInt(usul.unit);
  return (60 / bpm) * (4 / beatUnit);
}
